### ISSUE TITLE
[求助] 使用DynamicsCompressor 动态合成之后，如果拿到输出的MediaStream或者MediaStreamTrack?

### ISSUE THREAD

**Issue by chudongvip** [BenzLeung/WebAudioApiDemo#2]
### 感谢
首先感谢作者提供的这些DEMO以及文章，让我快速熟悉这些API！

### 提出困扰我的问题
当我有多个MediaStreamBufferSource时，我使用DynamicsCompressor动态合成之后，需要拿到合并之后的MediaStream，请问可以通过哪些方式或者哪些API，可以拿到辅助我拿到MedaiStream？

### 再次感谢
希望可以获得一个作者的联系方式，平时可以沟通一些技术问题，我是做实时音视频的

**Comment by BenzLeung** [comment]
Web Audio API 和 Media Streams API 是两回事，我之前也做过实时音视频，但现在很久没做了。已经忘记这两种 API 之间怎么转换啦。
我觉得可以在mdn找找，这类问题只要耐心翻番mdn的英文文档就会有答案的。

**Comment by chudongvip** [comment]
> Web Audio API 和 Media Streams API 是两回事，我之前也做过实时音视频，但现在很久没做了。已经忘记这两种 API 之间怎么转换啦。
> 我觉得可以在mdn找找，这类问题只要耐心翻番mdn的英文文档就会有答案的。

好的，我已经解决了，要不加个微信吧，以后有技术问题可以探讨一下，我是做实时音视频的

**Comment by BenzLeung** [comment]
不好意思，为确保安全和防止猎头骚扰，我不太愿意在Github上交换我的其他联系方式，见谅。

**Comment by chudongvip** [comment]
> 不太愿意在Github上交换我的其他联系方式，见

没关系，这个是我的微信的联系方式（cheampie），如果方便的话。
