### ISSUE TITLE
你好，有没有可能通过过滤器为实时音乐创建8 bit风格效果？

### ISSUE THREAD

**Issue by arrosev** [BenzLeung/WebAudioApiDemo#3]
正在寻找Web Audio API 如何为实时音乐创建复古8bit效果的资料，就是音乐已经有了，然后想给它增加8bit风格的滤镜，这种有可能实现吗？

**Comment by BenzLeung** [comment]
如果你说的是把mp3弄成复古效果，那么技术上非常难以实现。但如果你是说把**乐谱**弄成复古效果那就相对简单一些。建议你先找找有没有能**把mp3转换成乐谱**的方案（估计很难找），或者mp3转midi也行…… 找到了再考虑复古效果吧

**Comment by arrosev** [comment]
好吧，那可能就实现不了，我是给RPGMaker MZ写插件，因为这个软件自带的声效素材不是8-bit风格的，所以我本来想在音频滤镜那边看看有没有突破口。
